site_name: techAdventurerDocs
site_url: https://docs.strobe.be/it/
repo_url: https://github.com/techAdventurer/docs
repo_name: techAdventurer/docs
edit_uri: edit/main/docs

theme:
  name: material
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: deep orange
      accent: orange
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: deep orange
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode 
  font: false  
  icon:
    repo: fontawesome/brands/github
  features:
    - navigation.tabs
    - navigation.top
    - navigation.expand
    - navigation.sections
    
plugins:
  - git-revision-date-localized:
    type: date
    enable_creation_date: true

markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.tabbed
  - toc:
      toc_depth: 3
  - admonition
  - footnotes
  - attr_list
