site_name: techAdventurerDocs
site_url: https://docs.strobe.be/it/
repo_url: https://github.com/techAdventurer/docs
repo_name: techAdventurer/docs
theme:
  name: material
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: deep orange
      accent: orange
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: deep orange
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode 
  font: false
  logo: logo-strobe.png
  favicon: logo-strobe.png    
  icon:
    repo: fontawesome/brands/github
  features:
    - navigation.tabs
    - navigation.top
    - navigation.expand
    - navigation.sections
  extra:
    social:
       icon: fontawesome/solid/globe
       link: https://www.strobe.be
       name: Website

markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.tabbed
  - toc:
      toc_depth: 3
  - admonition
  - footnotes
  - attr_list
